# Generated by Django 5.1.1 on 2024-09-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=2000)),
                ('price', models.IntegerField(max_length=10)),
                ('guests', models.CharField(max_length=50)),
            ],
        ),
    ]
