# Generated by Django 4.2 on 2024-09-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_teammember_email_alter_teammember_user"),
        ("taskmanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "todo"),
                    ("progress", "progress"),
                    ("review", "review"),
                    ("done", "done"),
                ],
                default="todo",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="todolist",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.teammember",
            ),
        ),
        migrations.AddField(
            model_name="todolist",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
