# Generated by Django 4.2 on 2024-09-07 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskmanager", "0002_task_status_todolist_created_by_todolist_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 14, 36, 12, 874779, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("low", "low"), ("medium", "medium"), ("high", "high")],
                default="low",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 14, 36, 31, 927052, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "todo"),
                    ("progress", "progress"),
                    ("review", "review"),
                    ("done", "done"),
                ],
                default="todo",
                max_length=100,
            ),
        ),
    ]
