# Generated by Django 4.2 on 2024-09-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_teammember_email_alter_teammember_user"),
        ("taskmanager", "0004_remove_todoitem_todo_list_todolist_todo_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taskmanager.task",
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.teammanager",
            ),
        ),
    ]
