# Generated by Django 4.2 on 2024-09-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("createevent", "0002_rename_guests_eventdetails_event_cateogry_and_more"),
        ("taskmanager", "0005_todolist_task_alter_todolist_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="createevent.eventdetails",
            ),
        ),
    ]
