# Generated by Django 4.2.16 on 2024-09-08 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="inventory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.inventory",
            ),
            preserve_default=False,
        ),
    ]
