# Generated by Django 4.2.16 on 2024-09-08 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_teammember_email_alter_teammember_user"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whiteboard",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.businessaccount"
            ),
        ),
    ]
